#pragma once

namespace desm {

	enum eEvent {
		ENUM_CMD_TRACK = 1,
		ENUM_CMD_TRACK_CONNECTION = 2,
		ENUM_CMD_ISOLIERSTOSS = 3,
		ENUM_CMD_KILOMETER_DIRECTION = 4,
		ENUM_CMD_BALISE = 5,
		ENUM_CMD_SIGNAL = 6,
		ENUM_CMD_LOOP = 7,
		ENUM_CMD_WEICHE = 8,
		ENUM_CMD_TRAINPOSITION,
		ENUM_CMD_STARTSIMULATION,
		ENUM_CMD_STOPSIMULATION,
		ENUM_CMD_LOADSTRECKE
	};

};